### PR TITLE
add some missing commas

### PR DESCRIPTION
**Pull request by greyltc**

### CODE REVIEW

**Comment by poeschlr** [comment]
That was fast. Thanks

**Comment by poeschlr** [comment]
I started a build. Lets see what happens.

**Comment by poeschlr** [comment]
I fear i have bad news (unless i started the wrong build process that is):
https://api.travis-ci.org/v3/job/463094658/log.txt

Edit: Just in case i started a new build from the master branch instead of restarting the old one.
Edit2: looks better now. Sorry for the false alarm.

**Comment by greyltc** [comment]
What's #333? https://travis-ci.org/KiCad/kicad.github.io/builds/463581492

**Comment by poeschlr** [comment]
I think that one is the one i started after the first one failed.

**Pull request merged**
