### PR TITLE
allow travis to tag its builds

### PR DESCRIPTION
**Pull request by greyltc**
these tags will let GitHub keep an easily downloadable history (with weekly time resolution) of all the KiCad libraries

### CODE REVIEW

**Comment by poeschlr** [comment]
To which repo will these tags be added?

**Comment by greyltc** [comment]
this one ( https://github.com/KiCad/kicad.github.io )

**Comment by greyltc** [comment]
@poeschlr is there anything wrong with this PR?

**Comment by poeschlr** [comment]
Just forgot about it.

**Comment by greyltc** [comment]
maybe trigger a travis build manually to check that everything is okay here?

**Pull request merged**
